DATE = "DATE"
OZ_ZSP = "OZ_ZSP"
CLUSTER = "CLUSTER"

BACKLOG = "BACKLOG"
PARCEL_AMOUNT = "PARCEL_AMOUNT"
CHRISTMAS_SEASON = "CHRISTMAS_SEASON"
COVID_CASES = "COVID_CASES"
PUBLIC_HOLIDAYS = "PUBLIC_HOLIDAYS"
