# Basics
base_dir: "base_dir/"
target_column: "ABS_SICK_LEAVES"
# Filenames
filename_base_data: "stammdaten"
filename_sick_leave: "krankenstand"
filename_holidays_36: "feiertage_36"
filename_backlog: "backlog"
filename_parcel_amount: "parcel_amount"
filename_rescaling: "rescale_parameters"
# Time horizon
start_date: "2019-08-01"
end_date: "2023-11-30"
# CV steps
horizons: 12
number_cv_splits: 1
# Clustering
threshold_for_small_stations: 10
relevant_weeks: 26
n_jobs: 10
# Rescaling
rescaling_quantiles: [25, 75]
# Hyperparameter tuning
hidden_sizes: [16, 24, 32]
limit_train_batches: [0.25]
max_encoder_length: 26
batch_size: 126
